# Deployment do mongodb

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: mongouser
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: mongopwd
---

# Service do mongodb

apiVersion: v1
kind: Service
metadata:
  name: mongodbservice
  labels:
    run: mongodb 
spec:
  selector: 
    app: mongodb
  ports:
  - port: 27017
  type: ClusterIP
---

# Deployment da aplicação

apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicacao
spec:
  selector:
    matchLabels:
      app: aplicacao
  template:
    metadata:
      labels:
        app: aplicacao
    spec:
      containers:
      - name: aplicacao
        image: marcossales47/python_web:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_DB 
          value: admin
        - name: MONGODB_HOST
          value: localhost
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_USERNAME
          value: mongouser
        - name: MONGODB_PASSWORD
          value: mongopwd
---

# Service NodePort da aplicação

apiVersion: v1
kind: Service
metadata:
  name: nodeport
spec:
  selector:
    app: aplicacao
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30000
  type: NodePort














